# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QTalsim
                                 A QGIS plugin
 Dieses Plugin bildet für Talsim geeignete Elementarflächen.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-12
        copyright            : (C) 2023 by SYDRO Consult GmbH
        email                : l.treitler@sydro.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QTalsim class from file QTalsim.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qtalsim import QTalsim
    return QTalsim(iface)
