name: release qtalsim

on:
  release:
    types: published
   
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install qgis-plugin-ci
      run: pip install qgis-plugin-ci
      
    - name: Package Plugin
      run: qgis-plugin-ci package ${{ github.ref_name }}
      
    - name: Deploy plugin
      run: |
        qgis-plugin-ci release ${{ github.ref_name }} \
        --github-token ${{ secrets.GITHUB_TOKEN }} \
        --osgeo-username ${{ secrets.OSGEO_USER }} \
        --osgeo-password ${{ secrets.OSGEO_PASSWORD }}